### ISSUE TITLE
Comtradrclean - problem with input type

### ISSUE THREAD

**Issue by mapall** [MatthewSmith430/ITNr#1]
Thanks for the great package!
I stumbled on the following error while running `Comtradclean` function:

`Error: Must use a vector in `[`, not an object of class matrix.`

I figured out that the problem is on lines 188, 189, 193 and 194.
Function `as.vector()` does not change data type to vector and thus function `as.factor` on the next line generate mentioned error.

Possible workaround is to repace `as.vector()` function with `pull()`
I.e.:
row 188: `RR2 <- pull(RR, REGIONlist)`
row 193: `KK2<- pull(KK,INCOMElist)`

Hope it helps someone 🙂

**Comment by MatthewSmith430** [comment]
Thanks for the suggestion. I have implemented your workaround in the function 👍
