### ISSUE TITLE
Questions about Data Formating 

### ISSUE THREAD

**Issue by tdouthat** [MatthewSmith430/ITNr#2]
[Exports from 2003-2020_wCountryNames.xlsx](https://github.com/MatthewSmith430/ITNr/files/6193874/Exports.from.2003-2020_wCountryNames.xlsx)

I was wondering about formatting for data frames (in terms of column names , data format) and about using data obtained through the "tradestatistics package." Sorry if I have missed something very obvious. Could you clarify, or point me to the reference in the CRAN manual, to the names of the DF or .csv for the Comtradrclean() and/or WITSclean(). This was downloaded from  OEC (observatory of economic complexity). We need to do interpolation to sub-national units for or projects, so I I need to be able to substitute in some locations, e.g., Puerto Rico.  

Also, I am getting the following error when trying to recreate your code with 
ex_2 <- ct_search(reporters = "All", partners = c("USA","China", "Germany","Canada","Mexico"), trade_direction = "imports", start_date = "2016-01-01", end_date = "2016-12-31", commod_codes = "0702")

Error in eval(predvars, data, env) : object 'trade_value_usd' not found

**Comment by MatthewSmith430** [comment]
Some changes to the data (that you indicated in the link) are needed to use the `Comtradrclean` function. Essentially to use the `Comtradrclean`, you need to have a reporter_iso,partner_iso, trade_value_usd and year column. This applies even if you download the data directly from comtrade. Also - note that these functions are set up for import data. 

I have updated the function description to better clarify these points. Below are the changes you would need to make to the excel data (from the link) to use the `Comtradrclean` function: 

```{r cars1, eval=FALSE}
library(readxl)
library(dplyr)
library(ITNr)

DF<-read_excel("Exports.from.2003-2020_wCountryNames.xlsx")%>%
  filter(product=="Pneumatic tyres used")%>% #for one sector - otherwise you will need to aggregate the data if you want to consider all products together
  mutate(reporter_iso=countrycode(to,"country.name","iso3c"))%>% #the function needs iso names and the columns have been switched as the function is set up for import data
  mutate(partner_iso=countrycode(from,"country.name","iso3c"))%>%
  mutate(trade_value_usd=weight)%>%
  select(reporter_iso,partner_iso,trade_value_usd,year)

ITN<-Comtradrclean(DF,2003,TRUE,0)
```


If you are using data collected from the `Comtradr` package:
```{r cars2, eval=FALSE}
library(comtradr)
library(ITNr)
DF<- ct_search(reporters = "USA", 
                   partners = c("Germany", "France", "Japan", "Mexico"), 
                   trade_direction = "imports")

ITN<-Comtradrclean(DF,2003,TRUE,0)
```
